### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by superbuggy** [ga-wdi-lessons/devise#4]
What is the difference between encryption and hashing?
When would you choose one over the other?
Which one should be used for passwords?

**Comment by BaoPham92** [comment]
Encryption - Mix a string with a based algorithm converting and can be used to revert back to its original state.

We would only use encryption if we want to be able to access the original data at a certain point.

We would generally use hash moreover encryption since we want security stronger security for our users. 

Rather if we were to want to use a secure protocol of messaging and communicating with each other then we would use encryption. IE: Encrypting messages and one can decrypt if they want to have secure convos. Hash for overall security measures and safe keeping of user’s information.

**Comment by AskForTheWolf** [comment]
1) Hashing is taking a string/input and turning it into an unreadable value such that it would be impossible for someone who got the hashed value would not be able to return it to its original state.
Encryption takes your input/message, and with a key, turns it into an unreadable value so that the end user/storage can decrypt it with their key.

2) hashing would be best used when you're storing and comparing values like passwords, card #s, etc. Encryption is better suited for communicating or passing data between users/end points. 

3) Hashing should be used for passwords.

**Comment by tedlayea** [comment]
1. Hashing uses a fixed length of readable charcter, but it can`t be reversed.  
Encryption uses a un-fixed number of unreadable charcter, and it is reversible.
2. If you want to store password, use a hash.
3. Yes

**Comment by daniellefricke** [comment]
Encryption turns data into a series of unreadable characters w/o a fixed length
Hashing takes a string and turns it into a string or number. Hashing will never be able to recover the original password, but compares the hashed password to what the user inputs (which is also converted with hashing).

You use encryption if someone has the key to decrypt a message you're sending and they need to know the original password. You use hashing when you don't need the original password/text.

Hashing

**Comment by mjm5vp** [comment]
1) Encryption allows for a key to decrypt back to the original string while hashing does not.
2) You would use one depending one whether or not the original string needs to be retrieved for any reason.
3) Hashing should be used for passswords since they do not need to be converted back.

**Comment by Tchase44** [comment]
1. Hashing creates a fixed-length string out of and input. encryption scrambles data that can be decrypted with keys.
2.Hashes are good for data that does not need to be reverted. Ecyrption is good for data that needs to be sent, received, and read securely.
3. Passwords should be stored in a hash.

**Comment by RobLowe1992** [comment]
Hashes are a random string of a fixed length designed so that they can can't be converted into the original string. Encryption turns data into unreadable characters and can be restored to their decrypted form.

Hashing is generally more secure because it is designed to prevent you from reading the original string.

You should generally use a hash to store a password

**Comment by scottpiercew** [comment]
1. Hashing algorithms make sure the string can not be turned back into a readable form. The information stored for verification is only the information after the data has gone through the hashing algorithm. Encryption allows the encrypted data to be unencrypted, to be read again.

2. Hashing is used for storing passwords. Encryption is used for secure communications 

3. Hashing
